# Generated by Django 3.2.2 on 2021-08-03 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210707_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 8, 3, 11, 10, 14, 932131), max_length=255),
            preserve_default=False,
        ),
    ]
